[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[functions.getBannerList]
  memory = 1024 # 1GB
  timeout = 20  # 20초
  region = "ap-northeast-2"

# API 라우팅 개선
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA 라우팅 (모든 다른 경로는 index.html로)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
  