// 구글 스프레드시트 기반 예약 문의 데이터 생성 함수
export function generateSampleInquiries() {
  // 더 많은 다양한 샘플 데이터 생성 (실제 운영시에는 실제 데이터 사용)
  const sampleData = [
    {
      id: 1,
      title: "결혼식 사회자 문의",
      password: "*",
      author: "고은천",
      spouse: "라",
      phone: "010-0000-0000",
      mc: "최창은",
      weddingHall: "sdf",
      ceremonyType: "주례 없는 예식",
      secondPart: "2부 없음",
      ceremonyDate: "2025-07-07",
      ceremonyTime: "오전 11:59",
      howDidYouHear: "선택",
      linkUrl: "집업 정보를 관련 추가 정보",
      otherNotes: "기타 문의사항을 입력해보세요...",
      status: "확정",
      date: "2025-07-06",
    },
    {
      id: 2,
      title: "7월 결혼식 사회자 문의",
      password: "wedding123",
      author: "김민수",
      spouse: "이지은",
      phone: "010-1234-5678",
      mc: "고은���",
      weddingHall: "그랜드컨벤션센터",
      ceremonyType: "주례 있는 예식",
      secondPart: "2부 있음",
      ceremonyDate: "2025-07-15",
      ceremonyTime: "14:00",
      howDidYouHear: "네이버 검색",
      linkUrl: "웨딩홀 사회자",
      otherNotes:
        "야외 정원에서 진행 예정입니다. 마이크 시설 확인 부탁드립니다.",
      status: "확정",
      date: "2025-07-06",
    },
    {
      id: 3,
      title: "8월 여름 웨딩 사회자 예약",
      password: "summer2025",
      author: "박준호",
      spouse: "최수연",
      phone: "010-2345-6789",
      mc: "고은천",
      weddingHall: "라마다호텔",
      ceremonyType: "주례 없는 예식",
      secondPart: "2부 없음",
      ceremonyDate: "2025-08-10",
      ceremonyTime: "16:30",
      howDidYouHear: "지인 소개",
      linkUrl: "",
      otherNotes: "해외 거주 가족들이 많아 영어 멘트도 부탁드립니다.",
      status: "확정",
      date: "2025-07-06",
    },
    {
      id: 4,
      title: "9월 가을 결혼식 문의",
      password: "autumn9",
      author: "정다은",
      spouse: "김태우",
      phone: "010-3456-7890",
      mc: "최창은",
      weddingHall: "시티홀웨딩",
      ceremonyType: "주례 있는 예식",
      secondPart: "2부 있음",
      ceremonyDate: "2025-09-05",
      ceremonyTime: "13:00",
      howDidYouHear: "인스타그램",
      linkUrl: "",
      otherNotes: "가족 위주의 소규모 예식입니다. 따뜻한 분위기로 부탁드려요.",
      status: "확정",
      date: "2025-07-06",
    },
    {
      id: 5,
      title: "10월 결혼식 사회자 요청",
      password: "october",
      author: "서현우",
      spouse: "조미래",
      phone: "010-4567-8901",
      mc: "고은천",
      weddingHall: "벚꽃정원",
      ceremonyType: "주례 없는 예식",
      secondPart: "2부 있음",
      ceremonyDate: "2025-10-12",
      ceremonyTime: "15:30",
      howDidYouHear: "웨딩홀 및 플래너 소개",
      linkUrl: "벚꽃정원 웨딩홀",
      otherNotes: "야외 예식이라 날씨 확인 후 연락드리겠습니다.",
      status: "확정",
      date: "2025-07-06",
    },
    {
      id: 6,
      title: "11월 늦가을 웨딩 예약",
      password: "november",
      author: "윤서진",
      spouse: "한지민",
      phone: "010-5678-9012",
      mc: "최창은",
      weddingHall: "오션뷰채플",
      ceremonyType: "주례 있는 예식",
      secondPart: "2부 없음",
      ceremonyDate: "2025-11-20",
      ceremonyTime: "12:00",
      howDidYouHear: "유튜브",
      linkUrl: "",
      otherNotes: "바다가 보이는 곳에서 진행됩니다. 바람이 많이 불 수 있어요.",
      status: "확정",
      date: "2025-07-06",
    },
    {
      id: 7,
      title: "12월 연말 결혼식 문의",
      password: "december",
      author: "강민호",
      spouse: "송혜교",
      phone: "010-6789-0123",
      mc: "고은천",
      weddingHall: "팰리스호텔",
      ceremonyType: "주례 없는 예식",
      secondPart: "2부 있음",
      ceremonyDate: "2025-12-07",
      ceremonyTime: "18:00",
      howDidYouHear: "네이버 블로그",
      linkUrl: "https://blog.naver.com/wedding",
      otherNotes: "연말이라 많이 바쁘실 텐데 미리 예약합니다. 감사합니다.",
      status: "확정",
      date: "2025-07-06",
    },
    {
      id: 8,
      title: "내년 3월 봄 웨딩 예약",
      password: "spring26",
      author: "임수빈",
      spouse: "박보검",
      phone: "010-7890-1234",
      mc: "최창은",
      weddingHall: "가든파티웨딩홀",
      ceremonyType: "���례 있는 예식",
      secondPart: "2부 있음",
      ceremonyDate: "2026-03-15",
      ceremonyTime: "14:30",
      howDidYouHear: "구글 검색",
      linkUrl: "웨딩홀 사회자 추천",
      otherNotes: "펜션에서 진행하는 야외 웨딩입니다. 음향 장비 확인 필요해요.",
      status: "확정",
      date: "2025-07-06",
    },
    {
      id: 9,
      title: "4월 벚꽃시즌 웨딩 예약",
      password: "cherry",
      author: "최영준",
      spouse: "김고은",
      phone: "010-8901-2345",
      mc: "고은천",
      weddingHall: "드림팰리스",
      ceremonyType: "주례 없는 예식",
      secondPart: "2부 없음",
      ceremonyDate: "2026-04-18",
      ceremonyTime: "13:30",
      howDidYouHear: "네이버 카페 - 광주결",
      linkUrl: "",
      otherNotes: "정통 예식으로 진행하고 싶습니다. 격식있게 부탁드려요.",
      status: "확정",
      date: "2025-07-06",
    },
    {
      id: 10,
      title: "5월 가정의달 결혼식 문의",
      password: "family",
      author: "홍길동",
      spouse: "장희빈",
      phone: "010-9012-3456",
      mc: "최창은",
      weddingHall: "크리스탈볼룸",
      ceremonyType: "주례 ��는 예식",
      secondPart: "2부 있음",
      ceremonyDate: "2026-05-10",
      ceremonyTime: "11:00",
      howDidYouHear: "그 외 사이트",
      linkUrl: "https://wedding-site.com",
      otherNotes: "봄꽃이 만개하는 시기에 맞춰 로맨틱하게 진행하고 싶어요.",
      status: "확정",
      date: "2025-07-06",
    },
    // 추가 문의 데이터 (다양성을 위해)
    {
      id: 11,
      title: "6월 초여름 웨딩 사회자 문의",
      password: "june2025",
      author: "이수민",
      spouse: "박서준",
      phone: "010-1111-2222",
      mc: "고은천",
      weddingHall: "하늘정원",
      ceremonyType: "주례 없는 예식",
      secondPart: "2부 있음",
      ceremonyDate: "2025-06-21",
      ceremonyTime: "15:00",
      howDidYouHear: "네이버 카페 - 멕마웨",
      linkUrl: "",
      otherNotes: "친구들과 함께하는 즐거운 분위기로 진행하고 싶어요.",
      status: "확정",
      date: "2025-07-06",
    },
    {
      id: 12,
      title: "7월 휴가철 결혼식 예약",
      password: "vacation",
      author: "김현수",
      spouse: "정유미",
      phone: "010-2222-3333",
      mc: "최창은",
      weddingHall: "리조트웨딩홀",
      ceremonyType: "주례 있는 예식",
      secondPart: "2부 없음",
      ceremonyDate: "2025-07-26",
      ceremonyTime: "17:00",
      howDidYouHear: "네이버 카페 - 다이렉트 카페",
      linkUrl: "",
      otherNotes: "리조트에서 진행하는 특별한 웨딩입니다.",
      status: "문의",
      date: "2025-07-06",
    },
    {
      id: 13,
      title: "겨울 결혼식 사회자 예약 문의",
      password: "winter",
      author: "조민석",
      spouse: "한예슬",
      phone: "010-3333-4444",
      mc: "고은천",
      weddingHall: "스노우팰리스",
      ceremonyType: "주례 없는 예식",
      secondPart: "2부 있음",
      ceremonyDate: "2025-12-14",
      ceremonyTime: "14:00",
      howDidYouHear: "구글 검색",
      linkUrl: "겨울 웨딩 사회자",
      otherNotes: "눈 오는 날 로맨틱한 겨울 웨딩을 계획하고 있습니다.",
      status: "확정",
      date: "2025-07-05",
    },
    {
      id: 14,
      title: "주말 오후 결혼식 문의",
      password: "weekend",
      author: "신동엽",
      spouse: "유인나",
      phone: "010-4444-5555",
      mc: "최창은",
      weddingHall: "선데이채플",
      ceremonyType: "주례 있는 예식",
      secondPart: "2부 있음",
      ceremonyDate: "2025-08-17",
      ceremonyTime: "16:30",
      howDidYouHear: "그 외 사이트",
      linkUrl: "https://wedding-directory.com",
      otherNotes: "주말 오후 시간대로 예약하고 싶습니다.",
      status: "문의",
      date: "2025-07-05",
    },
    {
      id: 15,
      title: "해외 거주자 결혼식 문의",
      password: "overseas",
      author: "김태희",
      spouse: "비",
      phone: "010-5555-6666",
      mc: "고은천",
      weddingHall: "글로벌웨딩홀",
      ceremonyType: "주례 없는 예식",
      secondPart: "2부 없음",
      ceremonyDate: "2025-09-28",
      ceremonyTime: "11:30",
      howDidYouHear: "지인 소개",
      linkUrl: "",
      otherNotes: "해외 거주 중이라 화상으로 사전 상담 가능한지 문의드립니다.",
      status: "확정",
      date: "2025-07-04",
    },
  ];

  // localStorage에 저장
  localStorage.setItem("customerInquiries", JSON.stringify(sampleData));

  return sampleData;
}
